//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozaikaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class materialStash
    {
        public int id { get; set; }
        public Nullable<int> stashId { get; set; }
        public Nullable<int> materialId { get; set; }
    
        public virtual material material { get; set; }
        public virtual stash stash { get; set; }
    }
}
