//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozaikaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class materialOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materialOrder()
        {
            this.orderList = new HashSet<orderList>();
        }
    
        public int id { get; set; }
        public Nullable<int> supplierId { get; set; }
        public Nullable<int> workerId { get; set; }
        public Nullable<int> materialId { get; set; }
        public Nullable<int> stashId { get; set; }
    
        public virtual material material { get; set; }
        public virtual stash stash { get; set; }
        public virtual supplier supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderList> orderList { get; set; }
    }
}
