//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozaikaApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MozaikaEntities : DbContext
    {
        public MozaikaEntities()
            : base("name=MozaikaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<material> material { get; set; }
        public virtual DbSet<material_supplier> material_supplier { get; set; }
        public virtual DbSet<materialOrder> materialOrder { get; set; }
        public virtual DbSet<materialStash> materialStash { get; set; }
        public virtual DbSet<materialTypes> materialTypes { get; set; }
        public virtual DbSet<order_item> order_item { get; set; }
        public virtual DbSet<orderList> orderList { get; set; }
        public virtual DbSet<partner> partner { get; set; }
        public virtual DbSet<partner_order> partner_order { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<productType> productType { get; set; }
        public virtual DbSet<rating> rating { get; set; }
        public virtual DbSet<stash> stash { get; set; }
        public virtual DbSet<stash_material> stash_material { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
