//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozaikaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderList
    {
        public int id { get; set; }
        public Nullable<int> materialOrderId { get; set; }
        public Nullable<int> materialId { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> totalPrice { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual material material { get; set; }
        public virtual material material1 { get; set; }
        public virtual materialOrder materialOrder { get; set; }
    }
}
