//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozaikaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partner()
        {
            this.partner_order = new HashSet<partner_order>();
            this.rating1 = new HashSet<rating>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string organizationName { get; set; }
        public string inn { get; set; }
        public string directorFIO { get; set; }
        public string telNumber { get; set; }
        public string email { get; set; }
        public string logo { get; set; }
        public Nullable<int> ratingId { get; set; }
        public string sellingPlaces { get; set; }
        public Nullable<int> rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner_order> partner_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rating> rating1 { get; set; }
    }
}
