//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozaikaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partner_order()
        {
            this.order_item = new HashSet<order_item>();
        }
    
        public int id { get; set; }
        public int partner_id { get; set; }
        public System.DateTime order_date { get; set; }
        public decimal total_amount { get; set; }
        public string status { get; set; }
        public System.DateTime created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
        public virtual partner partner { get; set; }
    }
}
