//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozaikaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_item = new HashSet<order_item>();
        }
    
        public int id { get; set; }
        public Nullable<int> productTypeId { get; set; }
        public string packageSize { get; set; }
        public string name { get; set; }
        public string article { get; set; }
        public string desccription { get; set; }
        public string image { get; set; }
        public Nullable<decimal> minCostForPartner { get; set; }
        public Nullable<int> weightWithoutPackage { get; set; }
        public Nullable<int> weightWithPackage { get; set; }
        public string qualityCertificate { get; set; }
        public string standartNumber { get; set; }
        public Nullable<int> costChange { get; set; }
        public Nullable<int> selfCost { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> materialId { get; set; }
    
        public virtual material material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
        public virtual productType productType { get; set; }
    }
}
