//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MozaikaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int id { get; set; }
        public Nullable<int> partnerId { get; set; }
        public string timePeriod { get; set; }
        public Nullable<int> rating1 { get; set; }
    
        public virtual partner partner { get; set; }
    }
}
